import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  useUser,
} from '@clerk/nextjs'
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";
import ContextWrapper from "@/components/ContextWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <ContextWrapper>
          <Toaster />
          <Navbar />
          {children}
        </ContextWrapper>
      </html >
    </ClerkProvider>

  );
}
